import time
start_time = time.time()
print(start_time)
print("Time after the epoch is {}".format(time.time()))
date = time.gmtime(1621748323.6946957)
print(date)
local_time = time.localtime()
local_time = time.localtime(time.time())
print(local_time)
print(time.asctime(local_time))
print(time.asctime(date))
print(time.process_time())
print(time.process_time_ns())
end_time=time.time()
print(time.mktime(date))
print(end_time)
print(end_time - start_time)
